libraries:
  Filme:
    metadata_path:
    - pmm: imdb
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
  Filme-4K:
    metadata_path:
    - pmm: imdb
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
  Filme-Archiv:
    metadata_path:
    - pmm: imdb
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
  Filme-Original:
    metadata_path:
    - pmm: imdb
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
  Serien:
    metadata_path:
      - pmm: streaming
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: ratings
      template_variables:
        overlay_level: episode
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    - pmm: resolution
      template_variables:
        overlay_level: season
        horizontal_align: left
        vertical_align: top
    - pmm: resolution
      template_variables:
        overlay_level: episode
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
  Serien-4K:
    metadata_path:
      - pmm: streaming
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: ratings
      template_variables:
        overlay_level: episode
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    - pmm: resolution
      template_variables:
        overlay_level: season
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
  Serien-Archive:
    metadata_path:
      - pmm: streaming
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: ratings
      template_variables:
        overlay_level: episode
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    - pmm: resolution
      template_variables:
        overlay_level: season
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
  Serien-Original:
    metadata_path:
      - pmm: streaming
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: ratings
      template_variables:
        overlay_level: episode
        rating1: critic
        rating1_image: imdb
        horizontal_position: left
        vertical_position: bottom
        rating_alignment: horizontal
    - pmm: resolution
      template_variables:
        horizontal_align: left
        vertical_align: top
    - pmm: resolution
      template_variables:
        overlay_level: season
        horizontal_align: left
        vertical_align: top
    operations:
      mass_critic_rating_update: imdb
      delete_unmanaged_collections: true
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: <<plex_url>>
  token: <<plex_token>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                            # REQUIRED for the script to run
  apikey: <<token_apikey>>
  language: en
  cache_expiration: 60
  region:
omdb:
  apikey: <<omdb_apikey>>
  cache_expiration: 60
